version: "3.3"
services:
  db:
    image: postgres:14-alpine3.20
    container_name: spring_escola_ti_postegres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: spring_escola_ti
      POSTGRES_DB: spring_escola_ti
      POSTGRES_PASSWORD: 12345